name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: RustDoc
      run: cargo doc --verbose
    - name: fmt
      run: cargo fmt --verbose
    - name: Build
      run: cargo build --verbose
